### ISSUE TITLE
Local Docker image is not shared between job

### ISSUE THREAD

**Issue by trinhpham** [JCMais/docker-building-on-ci#2]
Hi @JCMais ,
Going through [your guide](https://circleci.com/blog/using-circleci-workflows-to-replicate-docker-hub-automated-builds/) I found that the local Docker image doesn't retain when build job is finished.
See more at [my failed build](https://app.circleci.com/pipelines/github/trinhpham/kubernetes-cloud-mysql-backup/9/workflows/9d496817-b818-4254-8125-072bdefad7ef)

Looking around, I found [this support guideline](https://support.circleci.com/hc/en-us/articles/360019182513-Build-a-Docker-image-in-one-job-and-use-it-in-another-job) which guides us to save the image to file for re-use.

I think you should update your (very) great guideline, so somebody (like me) can make thing up quicker.
Anw, thanks for your guide.

**Comment by JCMais** [comment]
Hi @trinhpham. Thanks for opening this issue.

This is mentioned in the guide, around the line `This happens because the jobs in a workflow are isolated from each other`.
